/**
 * One-time script to insert a header row at the top of Sheet1.
 * Run with: node add_sheet_header.js
 */
require('dotenv').config();
const { google } = require('googleapis');

const SHEET_ID = process.env.GOOGLE_SHEET_ID;

const HEADERS = [
  'Candidate Name',
  'Candidate Email',
  'Position / Designation',
  'Department',
  'Start Date',
  'End Date',
  'Mode',
  'Compensation',
  'Created At',
  'Email Status',
  'Offer ID',
  'Valid Until',
  'Approval Status',
  'Signed PDF URL',
  'Generated By',
  'Response Date'
];

async function main() {
  if (!process.env.GOOGLE_APPLICATION_CREDENTIALS || !SHEET_ID) {
    console.error('Missing GOOGLE_APPLICATION_CREDENTIALS or GOOGLE_SHEET_ID in .env');
    process.exit(1);
  }

  const auth = new google.auth.GoogleAuth({
    keyFile: process.env.GOOGLE_APPLICATION_CREDENTIALS,
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
  });

  const sheets = google.sheets({ version: 'v4', auth });

  // Step 1: Insert a blank row at position 0 (before all existing data)
  await sheets.spreadsheets.batchUpdate({
    spreadsheetId: SHEET_ID,
    resource: {
      requests: [
        {
          insertDimension: {
            range: {
              sheetId: 0,          // Sheet1 is always sheetId 0 by default
              dimension: 'ROWS',
              startIndex: 0,       // insert before row 1
              endIndex: 1
            },
            inheritFromBefore: false
          }
        }
      ]
    }
  });

  console.log('Blank row inserted at top.');

  // Step 2: Write the header values into the newly created row 1
  await sheets.spreadsheets.values.update({
    spreadsheetId: SHEET_ID,
    range: 'Sheet1!A1:J1',
    valueInputOption: 'USER_ENTERED',
    resource: {
      values: [HEADERS]
    }
  });

  console.log('✅ Header row written successfully:');
  console.log('   ' + HEADERS.join(' | '));
}

main().catch(err => {
  console.error('Failed:', err.message);
  process.exit(1);
});
