require('dotenv').config();
const { google } = require('googleapis');

const SHEET_ID = process.env.GOOGLE_SHEET_ID;

const FULL_HEADERS = [
  'Candidate Name',
  'Candidate Email',
  'Position / Designation',
  'Department',
  'Start Date',
  'End Date',
  'Mode',
  'Compensation',
  'Created At',
  'Email Status',
  'Offer ID',
  'Valid Until',
  'Approval Status',
  'Signed PDF URL',
  'Generated By',
  'Response Date'
];

async function updateHeaders() {
  if (!process.env.GOOGLE_APPLICATION_CREDENTIALS || !SHEET_ID) {
    console.error('Missing GOOGLE_APPLICATION_CREDENTIALS or GOOGLE_SHEET_ID in .env');
    process.exit(1);
  }

  const auth = new google.auth.GoogleAuth({
    keyFile: process.env.GOOGLE_APPLICATION_CREDENTIALS,
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
  });

  const sheets = google.sheets({ version: 'v4', auth });

  try {
    await sheets.spreadsheets.values.update({
      spreadsheetId: SHEET_ID,
      range: 'Sheet1!A1:P1', // Columns A to P (16 columns)
      valueInputOption: 'USER_ENTERED',
      resource: {
        values: [FULL_HEADERS]
      }
    });

    console.log('✅ Headers updated successfully in Sheet1!');
    console.log('   ' + FULL_HEADERS.join(' | '));
  } catch (err) {
    console.error('Failed to update headers:', err.message);
  }
}

updateHeaders();
