const sheets = require('../config/googleSheetsClient');

/**
 * Appends a user record to the 'Users' Google Sheet.
 * @param {Object} user - The user object from Supabase.
 */
async function appendUserToSheet(user) {
  if (!sheets) return; // Silent fail if Google Sheets is not configured

  try {
    const spreadsheetId = process.env.GOOGLE_SHEET_ID;
    if (!spreadsheetId) return;

    // Order matches: Email, PasswordHash, Name, Role, CreatedAt, ResetToken, ResetTokenExpires
    const values = [[
      user.email || '',
      user.password_hash || '',
      user.name || '',
      user.role || '',
      user.created_at || new Date().toISOString(),
      user.reset_token || '',
      user.reset_token_expires || ''
    ]];

    await sheets.spreadsheets.values.append({
      spreadsheetId,
      range: 'Users!A:G',
      valueInputOption: 'USER_ENTERED',
      resource: { values }
    });
    console.log('Appended user to Google Sheets');
  } catch (error) {
    console.error('Error appending user to Google Sheets:', error.message);
  }
}

/**
 * Appends an offer record to the 'Sheet1' Google Sheet.
 * @param {Object} offer - The offer object from Supabase.
 */
async function appendOfferToSheet(offer) {
  if (!sheets) return;

  try {
    const spreadsheetId = process.env.GOOGLE_SHEET_ID;
    if (!spreadsheetId) return;

    // Order matches Sheet1: 
    // Candidate Name, Candidate Email, Designation, Department, Start Date, End Date, 
    // Mode, Compensation, Created At, Email Status, ID, Valid Until, Status, 
    // Signed PDF URL, Generated By, Response Date
    const values = [[
      offer.candidate_name || '',
      offer.candidate_email || '',
      offer.designation || '',
      offer.department || '',
      offer.start_date || '',
      offer.end_date || '',
      offer.mode || '',
      offer.compensation || '',
      offer.created_at || new Date().toISOString(),
      offer.email_status || 'Pending',
      offer.id || '',
      offer.valid_until || '',
      offer.status || 'Pending',
      offer.signed_pdf_url || '',
      offer.generated_by || '',
      offer.response_date || ''
    ]];

    await sheets.spreadsheets.values.append({
      spreadsheetId,
      range: 'Sheet1!A:P',
      valueInputOption: 'USER_ENTERED',
      resource: { values }
    });
    console.log('Appended offer to Google Sheets');
  } catch (error) {
    console.error('Error appending offer to Google Sheets:', error.message);
  }
}

module.exports = {
  appendUserToSheet,
  appendOfferToSheet
};
