const sheets = require('../config/googleSheetsClient');

const SPREADSHEET_ID = process.env.GOOGLE_SHEET_ID;

/**
 * Appends a user record to the 'Users' Google Sheet.
 * @param {Object} user - The user object from Supabase.
 */
const appendUserToSheet = async (user) => {
  if (!sheets || !SPREADSHEET_ID) return;

  try {
    const values = [[
      user.email || '',
      user.password_hash || '',
      user.name || '',
      user.role || '',
      user.created_at || new Date().toISOString(),
      user.reset_token || '',
      user.reset_token_expires || ''
    ]];

    await sheets.spreadsheets.values.append({
      spreadsheetId: SPREADSHEET_ID,
      range: 'Users!A:A',
      valueInputOption: 'USER_ENTERED',
      insertDataOption: 'INSERT_ROWS',
      resource: { values }
    });
  } catch (error) {
    console.error('[SheetsSync] Failed to sync user:', error.message);
    const fs = require('fs');
    fs.appendFileSync('sheets_error.log', new Date().toISOString() + ' - User Sync Error: ' + error.message + '\n');
  }
};

/**
 * Async backup of new/updated offer to Google Sheets
 * Expected offerData: Full offer object from Supabase
 */
const syncOfferToSheet = async (offerData) => {
  if (!sheets || !SPREADSHEET_ID) return;
  
  try {
    // Append to "Sheet1" tab
    // Candidate Name, Candidate Email, Designation, Department, Start Date, End Date, 
    // Mode, Compensation, Created At, Email Status, ID, Valid Until, Status, 
    // Signed PDF URL, Generated By, Response Date
    const values = [[
      offerData.candidate_name || '',
      offerData.candidate_email || '',
      offerData.designation || '',
      offerData.department || '',
      offerData.start_date || '',
      offerData.end_date || '',
      offerData.mode || '',
      offerData.compensation || '',
      offerData.created_at || new Date().toISOString(),
      offerData.email_status || offerData.status || 'Pending',
      offerData.id || '',
      offerData.valid_until || '',
      offerData.status || 'Pending',
      offerData.signed_pdf_url || '',
      offerData.generated_by || offerData.manager_email || '',
      offerData.response_date || ''
    ]];

    await sheets.spreadsheets.values.append({
      spreadsheetId: SPREADSHEET_ID,
      range: 'Sheet1!A:A',
      valueInputOption: 'USER_ENTERED',
      insertDataOption: 'INSERT_ROWS',
      resource: { values }
    });
  } catch (error) {
    console.error('[SheetsSync] Failed to sync offer:', error.message);
    const fs = require('fs');
    fs.appendFileSync('sheets_error.log', new Date().toISOString() + ' - Offer Sync Error: ' + error.message + '\n');
  }
};

/**
 * Async backup of rejection event to Google Sheets
 */
const syncRejectionToSheet = async (rejectionData) => {
  if (!sheets || !SPREADSHEET_ID) return;
  
  try {
    await sheets.spreadsheets.values.append({
      spreadsheetId: SPREADSHEET_ID,
      range: 'Rejections!A:E',
      valueInputOption: 'USER_ENTERED',
      resource: {
        values: [[
          rejectionData.candidate_name,
          rejectionData.candidate_email,
          rejectionData.department || 'N/A',
          rejectionData.manager_email || 'Unknown',
          rejectionData.rejected_at || new Date().toISOString()
        ]]
      }
    });
  } catch (error) {
    console.error('[SheetsSync] Failed to sync rejection:', error.message);
  }
};

module.exports = { syncOfferToSheet, syncRejectionToSheet, appendUserToSheet };